/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package job_karyawan_toko;

/**
 *
 * @author Ahmad Habib
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.ComboBoxModel;
import javax.swing.table.DefaultTableModel;


public class tambah_hapus extends javax.swing.JFrame {

    /**
     * Creates new form tambah_hapus
     */
Connection conn;
ResultSet rs;
Statement stmt;
void lihat(){
try{
rs = stmt.executeQuery("select * from job_karyawan ");
Object[] baris = {"id_karyawan","nama_karyawan","gender_karyawan","tugas_bagian","shift_tugas","hari_kerja"};
DefaultTableModel tabmode = new DefaultTableModel(null,baris);
table_data.setModel(tabmode);
while(rs.next()){
String a = rs.getString("id_karyawan");
String b = rs.getString("nama_karyawan");
String c = rs.getString("gender_karyawan");
String d = rs.getString("tugas_bagian");
String e = rs.getString("shift_tugas");
String f = rs.getString("hari_kerja");

String[] data ={a,b,c,d,e,f};
tabmode.addRow(data);
}
}catch(Exception e ){
JOptionPane.showMessageDialog(null,e);
}
}
    public tambah_hapus() {
try{
Class.forName("com.mysql.jdbc.Driver");
conn = DriverManager.getConnection("jdbc:mysql://localhost/data_indomaret","root","");
stmt = conn.createStatement();

}catch(Exception e){
JOptionPane.showMessageDialog(null,e);
}
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id_karyawan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nama_karyawan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lakilaki = new javax.swing.JRadioButton();
        perempuan = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        job_bagian = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        malam = new javax.swing.JRadioButton();
        pagi = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        senin = new javax.swing.JCheckBox();
        selasa = new javax.swing.JCheckBox();
        rabu = new javax.swing.JCheckBox();
        kamis = new javax.swing.JCheckBox();
        jumat = new javax.swing.JCheckBox();
        sabtu = new javax.swing.JCheckBox();
        minggu = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_data = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        id_hapus = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("penugasan karyawan habib market cabang jagakarsa");

        jLabel2.setText("id_karyawan ");

        jLabel3.setText("nama karyawan : ");

        jLabel4.setText("gender   :");

        buttonGroup1.add(lakilaki);
        lakilaki.setText("laki-laki");

        buttonGroup1.add(perempuan);
        perempuan.setText("perempuan");

        jLabel5.setText("tugas bagian : ");

        job_bagian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pegawai gudang ", "pegawai gudang makanan basah ", "penjaga toko & cleaning service", "kasir ", "pengiriman barang" }));

        jLabel6.setText("shift tugas     : ");

        buttonGroup2.add(malam);
        malam.setText("malam");

        buttonGroup2.add(pagi);
        pagi.setText("pagi");
        pagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagiActionPerformed(evt);
            }
        });

        jLabel7.setText("hari kerja       : ");

        senin.setText("senin");

        selasa.setText("selasa");

        rabu.setText("rabu");

        kamis.setText("kamis");

        jumat.setText("jumat");

        sabtu.setText("sabtu");

        minggu.setText("minggu");

        jButton1.setText("tambah kayawan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("daftar karyawan : ");

        table_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_data);

        jButton2.setText("lihat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("hapus karyawan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        id_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_hapusActionPerformed(evt);
            }
        });

        jLabel10.setText("id karyawan yang ingin dihapus  : ");

        kembali.setText("kembali ke menu");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(malam)
                                                .addGap(18, 18, 18)
                                                .addComponent(pagi))
                                            .addComponent(nama_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lakilaki)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(perempuan))
                                            .addComponent(job_bagian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2)
                                        .addGap(142, 142, 142)
                                        .addComponent(kembali))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(37, 37, 37)
                                        .addComponent(id_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(senin)
                                                .addGap(18, 18, 18)
                                                .addComponent(kamis)
                                                .addGap(18, 18, 18)
                                                .addComponent(minggu))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(selasa)
                                                    .addComponent(rabu))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButton1)
                                                    .addComponent(sabtu)
                                                    .addComponent(jumat))
                                                .addGap(151, 151, 151)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(id_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButton3))))))
                                .addGap(0, 364, Short.MAX_VALUE)))
                        .addGap(64, 64, 64))))
            .addGroup(layout.createSequentialGroup()
                .addGap(436, 436, 436)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nama_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lakilaki)
                    .addComponent(perempuan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(job_bagian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(malam)
                        .addComponent(pagi)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(senin)
                        .addComponent(kamis)
                        .addComponent(minggu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selasa)
                    .addComponent(jumat)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rabu)
                    .addComponent(sabtu)
                    .addComponent(id_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jButton2)
                    .addComponent(kembali))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
try{
rs = stmt.executeQuery("select * from job_karyawan ");
Object[] baris = {"id_karyawan","nama_karyawan","gender_karyawan","tugas_bagian","shift_tugas","hari_kerja"};
DefaultTableModel tabmode = new DefaultTableModel(null,baris);
table_data.setModel(tabmode);
while(rs.next()){
String a = rs.getString("id_karyawan");
String b = rs.getString("nama_karyawan");
String c = rs.getString("gender_karyawan");
String d = rs.getString("tugas_bagian");
String e = rs.getString("shift_tugas");
String f = rs.getString("hari_kerja");

String[] data ={a,b,c,d,e,f};
tabmode.addRow(data);
}
}catch(Exception e ){
JOptionPane.showMessageDialog(null,e);
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
String senin2,selasa2,rabu2,kamis2,jumat2,sabtu2,minggu2;
String gender,shift;

// if else untuk mengambil nilai dari chekbox hari kerja 
if(senin.isSelected()){
senin2 = senin.getText();
}else{
senin2 = "";
}
if(selasa.isSelected()){
selasa2 = selasa.getText();
}else{
selasa2 = "";
}
if(rabu.isSelected()){
rabu2 = rabu.getText();
}else{
rabu2 = "";
}
if(kamis.isSelected()){
kamis2 = kamis.getText();
}else{
kamis2 = "";
}
if(jumat.isSelected()){
jumat2 = jumat.getText();
}else{
jumat2= "";
}
if(sabtu.isSelected()){
sabtu2= sabtu.getText();
}else{
sabtu2= "";
}
if(minggu.isSelected()){
minggu2 = minggu.getText();
}else{
minggu2 = "";
}


//if else untuk mengisi mengambil nilai dari radio button gender
if(lakilaki.isSelected()){
gender = lakilaki.getText();
}else{
gender = perempuan.getText();
}
//if else untuk mengisi mengambil nilai dari radio button shift kerja 
if(pagi.isSelected()){
shift = pagi.getText();
}else{
shift = malam.getText();
}

try{
stmt.executeUpdate("insert into job_karyawan values('"+id_karyawan.getText()+"','"+nama_karyawan.getText()+"','"+gender+"','"+job_bagian.getSelectedItem()+"','"+shift+"','"+senin2+","+selasa2+","+rabu2+","+kamis2+","+jumat2+","+sabtu2+","+minggu2+"')");
JOptionPane.showMessageDialog(null, "data karyawan baru berhasil dimasukan");
lihat();
}catch(Exception e){
JOptionPane.showMessageDialog(null, e);
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagiActionPerformed

    private void id_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_hapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_hapusActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
try{
stmt.executeUpdate("delete from job_karyawan where id_karyawan = '"+id_hapus.getText()+"'");
JOptionPane.showMessageDialog(null, "data karyawan degnan id = "+id_karyawan.getText()+" berhasil dihapus ");
}catch(Exception e){
JOptionPane.showMessageDialog(null, e);
lihat();
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
new menu().setVisible(true);
dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambah_hapus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambah_hapus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambah_hapus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambah_hapus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambah_hapus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField id_hapus;
    private javax.swing.JTextField id_karyawan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> job_bagian;
    private javax.swing.JCheckBox jumat;
    private javax.swing.JCheckBox kamis;
    private javax.swing.JButton kembali;
    private javax.swing.JRadioButton lakilaki;
    private javax.swing.JRadioButton malam;
    private javax.swing.JCheckBox minggu;
    private javax.swing.JTextField nama_karyawan;
    private javax.swing.JRadioButton pagi;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JCheckBox rabu;
    private javax.swing.JCheckBox sabtu;
    private javax.swing.JCheckBox selasa;
    private javax.swing.JCheckBox senin;
    private javax.swing.JTable table_data;
    // End of variables declaration//GEN-END:variables
}
