/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package job_karyawan_toko;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Ahmad Habib
 */
public class update_dan_cari extends javax.swing.JFrame {
Connection conn;
Statement stmt;
ResultSet rs;
    /**
     * Creates new form update_dan_cari
     */
void setelah_update(){
try{
rs = stmt.executeQuery("select * from job_karyawan where id_karyawan ='"+id_karyawan.getText()+"'");
Object[] baris = {"id_karyawan","nama_karyawan","gender_karyawan","tugas_bagian","shift_tugas","hari_kerja"};
DefaultTableModel tabmode2 = new DefaultTableModel(null,baris);
table_data.setModel(tabmode2);
while(rs.next()){
String a2 = rs.getString("id_karyawan");
String b2 = rs.getString("nama_karyawan");
String c2 = rs.getString("gender_karyawan");
String d2 = rs.getString("tugas_bagian");
String e2 = rs.getString("shift_tugas");
String f2 = rs.getString("hari_kerja");

String[] data ={a2,b2,c2,d2,e2,f2};
tabmode2.addRow(data);
}
}catch(Exception e ){
JOptionPane.showMessageDialog(null,e);
}
}
    public update_dan_cari() {
try{
Class.forName("com.mysql.jdbc.Driver");
conn = DriverManager.getConnection("jdbc:mysql://localhost/data_indomaret","root","");
stmt = conn.createStatement();
}catch(Exception e){
JOptionPane.showMessageDialog(null, e);
}
 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id_karyawan = new javax.swing.JTextField();
        senin = new javax.swing.JCheckBox();
        selasa = new javax.swing.JCheckBox();
        rabu = new javax.swing.JCheckBox();
        kamis = new javax.swing.JCheckBox();
        jumat = new javax.swing.JCheckBox();
        sabtu = new javax.swing.JCheckBox();
        minggu = new javax.swing.JCheckBox();
        update1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pagi = new javax.swing.JRadioButton();
        malam = new javax.swing.JRadioButton();
        update2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_data = new javax.swing.JTable();
        cari = new javax.swing.JButton();
        cari_karyawan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        kategori = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tampilkan = new javax.swing.JButton();
        kembali = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("update data karyawan dan pencarian data karyawan");

        jLabel2.setText("update hari kerja  : ");

        jLabel3.setText("id karyawan yang ingin di update : ");

        senin.setText("senin");

        selasa.setText("selasa");

        rabu.setText("rabu");

        kamis.setText("kamis");

        jumat.setText("jumat");
        jumat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumatActionPerformed(evt);
            }
        });

        sabtu.setText("sabtu");

        minggu.setText("minggu");

        update1.setText("update hari ");
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });

        jLabel4.setText("update shift tugas  : ");

        pagi.setText("pagi");

        malam.setText("malam");

        update2.setText("update shift");
        update2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update2ActionPerformed(evt);
            }
        });

        table_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table_data);

        cari.setText("cari karyawan ");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        jLabel5.setText("id karyawan yang dicari : ");

        kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pegawai gudang ", "pegawai gudang makanan basah ", "penjaga toko & cleaning service", "kasir ", "pengiriman barang" }));

        jLabel6.setText("tampilkan data karyawan berdasarkan kategori tugas bagian");

        tampilkan.setText("tampilkan ");
        tampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilkanActionPerformed(evt);
            }
        });

        kembali.setText("kembali ke menu ");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(301, 301, 301))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(id_karyawan))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(senin)
                                        .addGap(30, 30, 30)
                                        .addComponent(kamis)
                                        .addGap(18, 18, 18)
                                        .addComponent(minggu))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(selasa)
                                            .addComponent(rabu))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sabtu)
                                            .addComponent(jumat)))
                                    .addComponent(update1))
                                .addGap(172, 172, 172)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(update2)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pagi)
                                        .addGap(18, 18, 18)
                                        .addComponent(malam)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cari_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cari)
                        .addGap(75, 75, 75)
                        .addComponent(kembali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tampilkan)
                        .addGap(101, 101, 101))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(senin)
                            .addComponent(kamis)
                            .addComponent(minggu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selasa)
                            .addComponent(jumat)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pagi)
                            .addComponent(malam))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rabu)
                    .addComponent(sabtu))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(update1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(update2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cari)
                    .addComponent(cari_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tampilkan)
                    .addComponent(kembali))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jumatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumatActionPerformed

    private void tampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilkanActionPerformed
        // TODO add your handling code here:

try{
rs = stmt.executeQuery("select * from job_karyawan where tugas_bagian ='"+kategori.getSelectedItem()+"'");
Object[] baris = {"id_karyawan","nama_karyawan","gender_karyawan","tugas_bagian","shift_tugas","hari_kerja"};
DefaultTableModel tabmode = new DefaultTableModel(null,baris);
table_data.setModel(tabmode);
while(rs.next()){
String a = rs.getString("id_karyawan");
String b = rs.getString("nama_karyawan");
String c = rs.getString("gender_karyawan");
String d = rs.getString("tugas_bagian");
String e = rs.getString("shift_tugas");
String f = rs.getString("hari_kerja");

String[] data ={a,b,c,d,e,f};
tabmode.addRow(data);
}
}catch(Exception e ){
JOptionPane.showMessageDialog(null,e);
}
    }//GEN-LAST:event_tampilkanActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
try{
rs = stmt.executeQuery("select * from job_karyawan where id_karyawan ='"+cari_karyawan.getText()+"'");
Object[] baris = {"id_karyawan","nama_karyawan","gender_karyawan","tugas_bagian","shift_tugas","hari_kerja"};
DefaultTableModel tabmode2 = new DefaultTableModel(null,baris);
table_data.setModel(tabmode2);
while(rs.next()){
String a2 = rs.getString("id_karyawan");
String b2 = rs.getString("nama_karyawan");
String c2 = rs.getString("gender_karyawan");
String d2 = rs.getString("tugas_bagian");
String e2 = rs.getString("shift_tugas");
String f2 = rs.getString("hari_kerja");

String[] data ={a2,b2,c2,d2,e2,f2};
tabmode2.addRow(data);
}
}catch(Exception e ){
JOptionPane.showMessageDialog(null,e);
}
    }//GEN-LAST:event_cariActionPerformed

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
        // TODO add your handling code here:
String senin2,selasa2,rabu2,kamis2,jumat2,sabtu2,minggu2;

if(senin.isSelected()){
senin2 = senin.getText();
}else{
senin2 = "";
}
if(selasa.isSelected()){
selasa2 = selasa.getText();
}else{
selasa2 = "";
}
if(rabu.isSelected()){
rabu2 = rabu.getText();
}else{
rabu2 = "";
}
if(kamis.isSelected()){
kamis2 = kamis.getText();
}else{
kamis2 = "";
}
if(jumat.isSelected()){
jumat2 = jumat.getText();
}else{
jumat2= "";
}
if(sabtu.isSelected()){
sabtu2= sabtu.getText();
}else{
sabtu2= "";
}
if(minggu.isSelected()){
minggu2 = minggu.getText();
}else{
minggu2 = "";
}
// dibawah ini menjalankan perintah ke database untuk mengupdate data 
try{
stmt.executeUpdate("update job_karyawan set hari_kerja ='"+senin2+","+selasa2+","+rabu2+","+kamis2+","+jumat2+","+sabtu2+","+minggu2+"' where id_karyawan ='"+id_karyawan.getText()+"'");
JOptionPane.showMessageDialog(null, "hari kerja karyawan dengan id_karyawan ="+id_karyawan.getText()+"berhasil di update");

}catch(Exception e){
JOptionPane.showMessageDialog(null,e);
}
//fungsi dibawah ini yang di dalam try untuk menampilkan data yang baru saja diupdate
setelah_update();
    }//GEN-LAST:event_update1ActionPerformed

    private void update2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update2ActionPerformed
        // TODO add your handling code here:
String shift;
if(pagi.isSelected()){
shift = pagi.getText();
}else{
shift = malam.getText();
}

try{
stmt.executeUpdate("update job_karyawan set shift_tugas = '"+shift+"' where id_karyawan ='"+id_karyawan.getText()+"'");
JOptionPane.showMessageDialog(null, "shift tugas karyawan dengan id = "+id_karyawan.getText()+" berhasil di diganti");
}catch(Exception e){
JOptionPane.showMessageDialog(null, e);
}
setelah_update();
    }//GEN-LAST:event_update2ActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
new menu().setVisible(true);
dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update_dan_cari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update_dan_cari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update_dan_cari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update_dan_cari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_dan_cari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cari;
    private javax.swing.JTextField cari_karyawan;
    private javax.swing.JTextField id_karyawan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JCheckBox jumat;
    private javax.swing.JCheckBox kamis;
    private javax.swing.JComboBox<String> kategori;
    private javax.swing.JButton kembali;
    private javax.swing.JRadioButton malam;
    private javax.swing.JCheckBox minggu;
    private javax.swing.JRadioButton pagi;
    private javax.swing.JCheckBox rabu;
    private javax.swing.JCheckBox sabtu;
    private javax.swing.JCheckBox selasa;
    private javax.swing.JCheckBox senin;
    private javax.swing.JTable table_data;
    private javax.swing.JButton tampilkan;
    private javax.swing.JButton update1;
    private javax.swing.JButton update2;
    // End of variables declaration//GEN-END:variables
}
